version = 1

exclude_patterns = ["coverage/**"]

[[analyzers]]
name = "rust"
enabled = true

[analyzers.meta]
msrv = "stable"

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true