[package]
name = "sentinel"
version = "0.1.0"
edition = "2021"
authors = ["Developer Ramen <ramendev2009@gmail.com>"]
description = "An experimental utilitarian and administration assistant for Discord server owners."
readme = "README.md"
repository = "https://github.com/out-post/sentinel"
license = "MIT"
keywords = ["discord", "bot"]
publish = false

[dependencies]
serenity = "0.11"

